Added option to process input lists using Slurm.

diff --git a/voromarmotte b/voromarmotte
--- a/voromarmotte
+++ b/voromarmotte
@@ -20,6 +20,7 @@ Options:
     --output-vscript          string     output file path for the visualization script for Voronota-GL
     --output-pymol-vscript    string     output file path for the visualization script for PyMol
     --processors              number     maximum number of processors to run in parallel, default is 1
+    --sbatch-parameters       string     sbatch parameters to process '_list' input using Slurm, default is '' for no Slurm
     --help | -h                          flag to display help message and exit
 
 Standard output:
@@ -72,6 +73,7 @@ OUTPUT_TABLE_FILE=""
 OUTPUT_VSCRIPT=""
 OUTPUT_PYMOL_VSCRIPT=""
 MAX_PROCESSORS="1"
+SBATCH_PARAMETERS=""
 HELP_MODE="false"
 
 while [[ $# > 0 ]]
@@ -130,6 +132,10 @@ do
 		;;
 	--processors)
 		MAX_PROCESSORS="$OPTARG"
+		shift
+		;;
+	--sbatch-parameters)
+		SBATCH_PARAMETERS="$OPTARG"
 		shift
 		;;
 	-h|--help)
@@ -192,6 +198,20 @@ fi
 
 ################################################################################
 
+if [ -z "$MAX_PROCESSORS" ] || [ "$MAX_PROCESSORS" -ne "$MAX_PROCESSORS" ] || [ "$MAX_PROCESSORS" -lt "1" ]
+then
+	echo >&2 "Error: invalid number of processors '$MAX_PROCESSORS', must be a positive number"
+	exit 1
+fi
+
+if [ -n "$SBATCH_PARAMETERS" ]
+then
+	command -v sbatch &> /dev/null || { echo >&2 "Error: 'sbatch' executable not in binaries path"; exit 1; }
+	command -v squeue &> /dev/null || { echo >&2 "Error: 'squeue' executable not in binaries path"; exit 1; }
+fi
+
+################################################################################
+
 readonly TMPLDIR=$(mktemp -d)
 trap "rm -r $TMPLDIR" EXIT
 
@@ -199,7 +219,7 @@ trap "rm -r $TMPLDIR" EXIT
 
 if [ "$INFILE" == "_list" ]
 then
-	cat | egrep . | sort | uniq > "$TMPLDIR/input_list"
+	cat | grep -E . | sort | uniq > "$TMPLDIR/input_list"
 	
 	if [ ! -s "$TMPLDIR/input_list" ]
 	then
@@ -231,7 +251,29 @@ then
 		awk -v outdir="$TMPLDIR/children_tables" '{print "--input " $1 " --output-table-file " outdir "/" NR ".pdb"}'
 	fi
 	} \
-	| xargs -L 1 -P "$PROCESSORS_FOR_LEVEL_ONE" "$ZEROARG" "${ALLARGS[@]}" --processors "$PROCESSORS_FOR_LEVEL_TWO"
+	| {
+		if [ -z "$SBATCH_PARAMETERS" ]
+		then
+			xargs -L 1 -P "$PROCESSORS_FOR_LEVEL_ONE" "$ZEROARG" "${ALLARGS[@]}" --processors "$PROCESSORS_FOR_LEVEL_TWO"
+		else
+			mkdir -p "${TMPLDIR}/slurm_logs"
+			
+			xargs -L 1 sbatch -o "${TMPLDIR}/slurm_logs/slurmjob-%j.out" -e "${TMPLDIR}/slurm_logs/slurmjob-%j.err" $SBATCH_PARAMETERS "$ZEROARG" "${ALLARGS[@]}" --processors 1 \
+			| grep -E '^Submitted batch job ' \
+			| awk '{print $4}' \
+			> "$TMPLDIR/slurm_job_ids"
+			
+			sleep 1
+			REMAINING_SLURM_JOBS="$(squeue | grep -f "$TMPLDIR/slurm_job_ids" | wc -l)"
+			while [ "$REMAINING_SLURM_JOBS" -gt "0" ]
+			do
+				sleep 2
+				REMAINING_SLURM_JOBS="$(squeue | grep -f "$TMPLDIR/slurm_job_ids" | wc -l)"
+			done
+			
+			find "$TMPLDIR/slurm_logs/" -type f -not -empty | xargs -L 1 cat >&2
+		fi
+	}
 	
 	find "$TMPLDIR/children_tables" -type f -not -empty \
 	| sort \
