Improved multipoint mutation sampling mode.

diff --git a/tools/suggest-mutations-to-change-binding-stability b/tools/suggest-mutations-to-change-binding-stability
--- a/tools/suggest-mutations-to-change-binding-stability
+++ b/tools/suggest-mutations-to-change-binding-stability
@@ -7,10 +7,12 @@ export LC_ALL=C
 
 MODE="$1"
 N_TO_OUTPUT="$2"
+MAX_MUTATIONS="$3"
+LASTARG="$4"
 
-if [ -z "$MODE" ] || [ -z "$N_TO_OUTPUT" ] || [ -n "$LASTARG" ]
+if [ -z "$MODE" ] || [ -z "$N_TO_OUTPUT" ] || [ -z "$MAX_MUTATIONS" ] || [ -n "$LASTARG" ]
 then
-	echo >&2 "Error: invalid number of command-line arguments, must be exactly two - mode ('stabilize' or 'destabilize') and number of results to otputput."
+	echo >&2 "Error: invalid number of command-line arguments, must be exactly three - mode ('stabilize' or 'destabilize'), number of results to otputput, max number of simultaneous mutations."
 	exit 1
 fi
 
@@ -48,7 +50,7 @@ cat ./table_initial \
 cd - &> /dev/null
 
 cat "${TMPLDIR}/table_m1" \
-| ./sample-multiple-mutations 42 1 10 "$N_TO_OUTPUT" \
+| ./sample-multiple-mutations 42 1 "$MAX_MUTATIONS" "$N_TO_OUTPUT" \
 | tr ' ' '_'
 
 exit 0
diff --git a/voromarmotte b/voromarmotte
--- a/voromarmotte
+++ b/voromarmotte
@@ -266,18 +266,32 @@ if [ -n "$MUTATE_SIDECHAINS" ]
 then
 	if [[ "$MUTATE_SIDECHAINS" == "stabilize-interface-"* ]] || [[ "$MUTATE_SIDECHAINS" == "destabilize-interface-"* ]]
 	then
-		read OPTIMIZATION_MODE MUTATE_CHAIN MAX_TRIES <<< "$(echo ${MUTATE_SIDECHAINS} | tr '-' ' ' | tr '_' ' ' | tr '=' ' ' | tr ':' ' ' | awk '{print $1 " " $3 " " $4}')"
+		read OPTIMIZATION_MODE MUTATE_CHAIN MAX_TRIES MAX_MUTATIONS <<< "$(echo ${MUTATE_SIDECHAINS} | tr '-' ' ' | tr '_' ' ' | tr '=' ' ' | tr ':' ' ' | awk '{print $1 " " $3 " " $4 " " $5}')"
 		
-		"$ZEROARG" "${ALLARGS[@]}" --mutate-sidechains "interface-${MUTATE_CHAIN}-every" --output-table-file _stdout > "${TMPLDIR}/single_mutations_table"
+		if [ -z "$MUTATE_CHAIN" ] || [ -z "$MAX_TRIES" ] || [ -z "$MAX_MUTATIONS" ]
+		then
+			echo >&2 "Error: invalid interface mutation mode specifier, it must contain chain name, number of samples, max number of mutations - e.g. 'stabilize-interface-A-1000-10'."
+			exit 1
+		fi
+		
+		"$ZEROARG" "${ALLARGS[@]}" --mutate-sidechains "interface-${MUTATE_CHAIN}-every" --output-table-file _stdout \
+		> "${TMPLDIR}/single_mutations_table"
+		
+		cat "${TMPLDIR}/single_mutations_table" \
+		| ${SCRIPTDIR}/tools/suggest-mutations-to-change-binding-stability "$OPTIMIZATION_MODE" "$MAX_TRIES" "$MAX_MUTATIONS" \
+		| grep -E '.' \
+		> "${TMPLDIR}/suggested_multipoint_mutations"
 		
 		{
 			cat "${TMPLDIR}/single_mutations_table"
 			
-			cat "${TMPLDIR}/single_mutations_table" \
-			| ${SCRIPTDIR}/tools/suggest-mutations-to-change-binding-stability "$OPTIMIZATION_MODE" "$MAX_TRIES" \
-			| sed "s|^|${INFILE} |" \
-			| "$ZEROARG" "${ALLARGS[@]}" --input _list --mutate-sidechains _list --output-table-file _stdout \
-			| tail -n +2
+			if [ -s "${TMPLDIR}/suggested_multipoint_mutations" ]
+			then
+				cat "${TMPLDIR}/suggested_multipoint_mutations" \
+				| sed "s|^|${INFILE} |" \
+				| "$ZEROARG" "${ALLARGS[@]}" --input _list --mutate-sidechains _list --output-table-file _stdout \
+				| tail -n +2
+			fi
 		} \
 		| {
 			if [ "$OPTIMIZATION_MODE" == "stabilize" ]
